export const SET_USER_DATA = 'SET_USER_DATA';
export const GET_ERRORS = 'GET_ERRORS';
export const IS_LOADING = 'IS_LOADING';
export const GET_ALL_PROFILES ='GET_ALL_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const PORFILE_NOT_FOUND ='PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';